// backend/internal/models/client_status_email.go
package models

import "time"

// ClientStatusEmail is an AI-drafted weekly status update for one client,
// covering completed tasks, logged hours, and invoice activity for
// [PeriodStart, PeriodEnd]. Generated by
// services.RunClientStatusEmailDrafts, it always starts as "pending" and is
// never auto-sent - a super_admin must review (and may edit Subject/Body)
// before approving, mirroring the InvoiceReminder/InvoiceNotice
// approve-then-send pattern. Sending uses the approving user's own connected
// Gmail account (see handlers/client_status_email_handler.go), not a
// service account.
type ClientStatusEmail struct {
	ID             uint       `json:"id" gorm:"primaryKey"`
	ClientID       uint       `json:"client_id" gorm:"not null"`
	PeriodStart    time.Time  `json:"period_start" gorm:"type:date;not null"`
	PeriodEnd      time.Time  `json:"period_end" gorm:"type:date;not null"`
	Subject        string     `json:"subject" gorm:"type:text;not null"`
	Body           string     `json:"body" gorm:"type:text;not null"`
	Status         string     `json:"status" gorm:"size:20;not null;default:'pending'"`
	CreatedAt      time.Time  `json:"created_at"`
	SentBy         *uint      `json:"sent_by"`
	SentAt         *time.Time `json:"sent_at"`
	GmailMessageID string     `json:"gmail_message_id" gorm:"size:255"`
	DismissedBy    *uint      `json:"dismissed_by"`
	DismissedAt    *time.Time `json:"dismissed_at"`
}

func (ClientStatusEmail) TableName() string { return "client_status_emails" }

type ClientStatusEmailWithNames struct {
	ClientStatusEmail
	ClientName string `json:"client_name"`
}

type ClientStatusEmailListResponse struct {
	Success bool                         `json:"success"`
	Message string                       `json:"message,omitempty"`
	Emails  []ClientStatusEmailWithNames `json:"emails,omitempty"`
}

type ClientStatusEmailActionResponse struct {
	Success bool               `json:"success"`
	Message string             `json:"message,omitempty"`
	Email   *ClientStatusEmail `json:"email,omitempty"`
}

// ClientStatusEmailApproveRequest optionally overrides the AI-drafted
// Subject/Body with the super_admin's edits before sending.
type ClientStatusEmailApproveRequest struct {
	Subject string `json:"subject"`
	Body    string `json:"body"`
}
